using System.Collections.Generic;

namespace TableDescriptor
{
    public interface Descriptor
    {
        string Schema { get; set; }
        string Table { get; }
        void Describe();

        /// <summary>
        /// All non-transient properties; these properties have a counterpart in the database
        /// </summary>
        IList<PropertyToColumn> All { get; }

        /// <summary>
        /// All properties that may make up a database insert; anything that is not transient or generated by the database (keys and computed fields)
        /// </summary>
        IList<PropertyToColumn> Insertable { get; }

        /// <summary>
        /// The table identity, if it exists
        /// </summary>
        PropertyToColumn Identity { get; }

        /// <summary>
        /// All columns that are set by the database implicitly
        /// </summary>
        IList<PropertyToColumn> Computed { get; }

        /// <summary>
        /// All columns that are keys
        /// </summary>
        IList<PropertyToColumn> Keys { get; }

        /// <summary>
        /// All columns that must be set by the client explicitly
        /// </summary>
        IList<PropertyToColumn> Assigned { get; }
    }
}
