//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebnf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ebnf.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting rule definition &lt;=&gt;, but found &lt;{0}&gt;..
        /// </summary>
        public static string ExpectedDefinition {
            get {
                return ResourceManager.GetString("ExpectedDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting expression factor, but found &lt;{0}&gt;..
        /// </summary>
        public static string ExpectedFactor {
            get {
                return ResourceManager.GetString("ExpectedFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A grouping was declared but not completed. Groupings must be enclosed with &apos;(&apos; and &apos;)&apos;..
        /// </summary>
        public static string HangingGrouping {
            get {
                return ResourceManager.GetString("HangingGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An option was declared but not completed. Options must be enclosed with &apos;[&apos; and &apos;]&apos;..
        /// </summary>
        public static string HangingOption {
            get {
                return ResourceManager.GetString("HangingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A repetition was declared but not completed. Options must be enclosed with &apos;{&apos; and &apos;}&apos;..
        /// </summary>
        public static string HangingRepetition {
            get {
                return ResourceManager.GetString("HangingRepetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A special sequence was declared but not completed. Special sequences must be enclosed with &apos;?&apos; and &apos;?&apos;..
        /// </summary>
        public static string HangingSpecialSequence {
            get {
                return ResourceManager.GetString("HangingSpecialSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rules found in token stream..
        /// </summary>
        public static string NoRulesFound {
            get {
                return ResourceManager.GetString("NoRulesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules must begin with an identifier..
        /// </summary>
        public static string RulesMustBeginWithIdentifier {
            get {
                return ResourceManager.GetString("RulesMustBeginWithIdentifier", resourceCulture);
            }
        }
    }
}
